=== AyushAcharya07/WTL/Assignment_3/states.dtd
<!ELEMENT states (state*)>
<!ELEMENT state (name, capital, districts, population)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT capital (#PCDATA)>
<!ELEMENT districts (#PCDATA)>
<!ELEMENT population (#PCDATA)>

=== AyushAcharya07/WTL/Assignment_3/states.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE states SYSTEM "states.dtd">
<?xml-stylesheet type="text/xsl" href="states.xsl"?>
<states>
  <state>
    <name>Maharashtra</name>
    <capital>Mumbai</capital>
    <districts>36</districts>
    <population>112374333</population>
  </state>
  <state>
    <name>Uttar Pradesh</name>
    <capital>Lucknow</capital>
    <districts>75</districts>
    <population>199812341</population>
  </state>
  <state>
    <name>Andhra Pradesh</name>
    <capital>Amaravati</capital>
    <districts>13</districts>
    <population>49506799</population>
  </state>
  <state>
    <name>Arunachal Pradesh</name>
    <capital>Itanagar</capital>
    <districts>25</districts>
    <population>1383727</population>
  </state>
  <state>
    <name>Assam</name>
    <capital>Dispur</capital>
    <districts>33</districts>
    <population>31205576</population>
  </state>
  <state>
    <name>Bihar</name>
    <capital>Patna</capital>
    <districts>38</districts>
    <population>104099452</population>
  </state>
  <state>
    <name>Chhattisgarh</name>
    <capital>Raipur</capital>
    <districts>27</districts>
    <population>25545198</population>
  </state>
  <state>
    <name>Goa</name>
    <capital>Panaji</capital>
    <districts>2</districts>
    <population>1458545</population>
  </state>
  <state>
    <name>Gujarat</name>
    <capital>Gandhinagar</capital>
    <districts>33</districts>
    <population>60439692</population>
  </state>
  <state>
    <name>Haryana</name>
    <capital>Chandigarh</capital>
    <districts>22</districts>
    <population>25351462</population>
  </state>
  <state>
    <name>Himachal Pradesh</name>
    <capital>Shimla</capital>
    <districts>12</districts>
    <population>6864602</population>
  </state>
  <state>
    <name>Jharkhand</name>
    <capital>Ranchi</capital>
    <districts>24</districts>
    <population>32988134</population>
  </state>
  <state>
    <name>Karnataka</name>
    <capital>Bengaluru</capital>
    <districts>30</districts>
    <population>61095297</population>
  </state>
  <state>
    <name>Kerala</name>
    <capital>Thiruvananthapuram</capital>
    <districts>14</districts>
    <population>33406061</population>
  </state>
  <state>
    <name>Madhya Pradesh</name>
    <capital>Bhopal</capital>
    <districts>52</districts>
    <population>72626809</population>
  </state>
  
  <state>
    <name>Manipur</name>
    <capital>Imphal</capital>
    <districts>16</districts>
    <population>2570390</population>
  </state>
  <state>
    <name>Meghalaya</name>
    <capital>Shillong</capital>
    <districts>11</districts>
    <population>2966889</population>
  </state>
  <state>
    <name>Mizoram</name>
    <capital>Aizawl</capital>
    <districts>8</districts>
    <population>1097206</population>
  </state>
  <state>
    <name>Nagaland</name>
    <capital>Kohima</capital>
    <districts>11</districts>
    <population>1978502</population>
  </state>
  <state>
    <name>Odisha</name>
    <capital>Bhubaneswar</capital>
    <districts>30</districts>
    <population>41974218</population>
  </state>
  <state>
    <name>Punjab</name>
    <capital>Chandigarh</capital>
    <districts>22</districts>
    <population>27743338</population>
  </state>
  <state>
    <name>Rajasthan</name>
    <capital>Jaipur</capital>
    <districts>33</districts>
    <population>68548437</population>
  </state>
  <state>
    <name>Sikkim</name>
    <capital>Gangtok</capital>
    <districts>6</districts>
    <population>691000</population>
  </state>
</states>
